Can't include LCMS2 on Windows at the moment.
On the libtiff 4.0 variant, I get package compatibility errors:

```
Package jpeg conflicts for:
lcms2 -> jpeg[version='>=9b,<10a|>=9c,<10a|>=9d,<10a']
jpeg=9
libtiff=4.0 -> jpeg[version='9.*|>=9b,<10a|>=9c,<10a']

Package libtiff conflicts for:
libtiff=4.0
lcms2 -> libtiff[version='>=4.1.0,<5.0a0']
```

On libtiff 4.1, I get a separate issue during test (that is not obviously
related to LCMS?):

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py"
import: 'PIL'
import: 'PIL.Image'
D:\bld\pillow_1593795315516\_test_env\lib\site-packages\PIL\Image.py:115: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: "7.2.0"
Pillow version: 7.2.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "D:\bld\pillow_1593795315516\test_tmp\run_test.py", line 5, in <module>
    import PIL.Image
  File "D:\bld\pillow_1593795315516\_test_env\lib\site-packages\PIL\Image.py", line 100, in <module>
    "Pillow version: %s" % (getattr(core, "PILLOW_VERSION", None), __version__)
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: "7.2.0"
Pillow version: 7.2.0
```